# 7-20-PPTT-Entrance
Ministry of Education

7/20 Pre Primary Teacher Training(PPTT) Entrance Files

၁။ စစ်ကိုင်းပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Sagaing.pdf


၂။ ကျိုင်းတုံပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Shan%2520%2528E%2529.pdf

၃။ ဘိုက​လေးပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Bokalay.pdf

၄။ ထားဝယ်ပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Dawei.pdf

၅။ ရန်ကင်းပညာ​ရေး​​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Yankin.pdf

၆။ သင်္ကန်းကျွန်းပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Thingyung.pdf

၇။ ​တောင်ငူပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Taungoo.pdf
​
၈။ ​တောင်ကြီးပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Taunggyi.pdf

၉။ ပြည်ပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Pyay.pdf

၁၀။ ပုသိမ်ပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Pathein.pdf

၁၁။ ပခုက္ကူပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Pakokkuu.pdf

၁၂။ မြစ်ကြီးနားပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Myitkyina.pdf

၁၃။ ​မြောင်းမြပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Myaung%2520Mya.pdf 

၁၄။ မုံရွာပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Monywa.pdf

၁၅။ မိတ္ထီလာပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Meikhtila.pdf
​
၁၆။ ​မော်လမြိုင်ပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Mawlamyaing.pdf 

၁၇။ မန္တ​လေးပညာ​​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Mandalay.pdf

၁၈။ မ​ကွေးပညာ​ရေး​​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Magway.pdf 

၁၉။ လွိုင်​ကော်ပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Loikaw.pdf 

၂၀။ လားရိူးပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Lasho.pdf
​
၂၁။ ​ကျောက်ဖြူ​ပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Kyauk%2520Phyu.pdf

၂၂။ ဘားအံပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Hpa-An.pdf 

၂၃။ လှည်းကူးပညာ​ရေး​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Hlegu.pdf 

၂၄။ ဟားခါးပညာ​ရေး​​ကောလိပ်
http://www.moe.gov.mm/sites/all/libraries/pdf.js/web/viewer.html?file=http%3A%2F%2Fwww.moe.gov.mm%2Fsites%2Fdefault%2Ffiles%2FPPTT-2020-Hakha.pdf

Contact me for this problem: https://www.facebook.com/official.acc.heinmyatlinn
